services:
  mongodb:
    image: mongo
    container_name: mongo_inter
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongo_inter
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo

  pgdb:
    image: postgres
    container_name: pg_inter
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pg_inter
    volumes:
      - pgdata:/data/postgres
    network_mode: host

volumes:
  dbdata:
    driver: local
  pgdata:
    driver: local
